[package]
name = "lambda-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.8"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.0", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
